steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
     - 'build'
     - '-t'
     - 'asia-northeast1-docker.pkg.dev/kokoballcicd/pika-repo/pika2:lastest'
     - '.'
images: ['asia-northeast1-docker.pkg.dev/kokoballcicd/pika-repo/pika2:lastest']
