steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kokoballcicd/pika:stable', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kokoballcicd/pika:stable']

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "pika",
        "--image",
        "gcr.io/kokoballcicd/pika:stable",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--port",
        "80",
        "--allow-unauthenticated",
      ]


