steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/kokoballcicd/pika-repo/pika2:lastest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/kokoballcicd/pika-repo/pika2:lastest']

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "pika2",
        "--image",
        "asia-northeast1-docker.pkg.dev/kokoballcicd/pika-repo/pika2:lastest",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--port",
        "80",
        "--allow-unauthenticated",
      ]


